
version: '3.8'

services:
  db:
    image: postgres:12.18-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "db-data:/var/lib/postgresql/data"

  web:
    build: .
    command:
      bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
    db-data:
